### ISSUE TITLE
ethUtil.addHexPrefix is not a function

### ISSUE THREAD

**Issue by mariyaVj** [BitGo/BitGoJS#74]
I am trying to send ethereum coins to an address, by using the following method, 

```
      var amount = req.body.amount * 1e18;
      bitgo.coin('teth').wallets().get({id: id}, (err, wallet) => {
            if (err) {
                  console.log("Error getting wallet!");
            }
           wallet.send({ address: destinationAddress, amount: amount.toString(), walletPassphrase: 
 walletPassphrase }).then((transaction) => {
                  if (err) {
                     console.log(err)
                  }else {
                   console.log('got result');
                  }
             });
         }); 
```

But it is always giving me an error inside the bitgo module as follows 

```

TypeError: ethUtil.addHexPrefix is not a function
0|www      |     at /home/united/api/node_modules/bitgo/src/v2/coins/eth.js:89:75
0|www      |     at Array.forEach (native)
0|www      |     at BaseCoin.Eth.getOperationSha3ForExecuteAndConfirm (/home/united/api/node_modules/bitgo/src/v2/coins/eth.js:88:14)
0|www      |     at BaseCoin.Eth.signTransaction (/home/united/api/node_modules/bitgo/src/v2/coins/eth.js:126:30)
```

Can anyone help on this ?

**Comment by jlopp** [comment]
Are you using the latest version of BitGoJS? Have you tried running a "npm install" since your last update? If that still doesn't work, try deleting the node_modules directory and npm installing again.

**Comment by thomas4019** [comment]
It sound like ethereumjs-util, a required dependency to use Ethereum is not installing correctly. Can you try reinstalling it by running the following command: `npm installl ethereumjs-util`. Also can you let us know your npm version which can be found by running `npm --version`. Thanks!

**Comment by mariyaVj** [comment]
I tried with that, but it is also not working in my case, my npm version is 3.10.10 and the version ethereumjs-util is ^5.1.2", Still getting issues

**Comment by thomas4019** [comment]
Hi Mariya, can you please upgrade to npm 4 or 5 and try again? If it's still not working, please give us the output from running `npm ls`.

**Comment by thomas4019** [comment]
Hi Mariya, can you please upgrade to npm 4 or 5 and try again? If it's still not working, please give us the output from running `npm ls`.

**Comment by thomas4019** [comment]
Hi Mariya, can you please upgrade to npm 4 or 5 and try again? If it's still not working, please give us the output from running `npm ls`.

**Comment by mariyaVj** [comment]
I have upgrade npm to 5 , then when tried to install bitgo it is giving me an access error, now it seems like I couldn't install bitgo . It throwing me the following error 

`npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/dabura667/bitcoinjs-lib.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! `

I tried to install it in my local system too , but getting the same issue

**Comment by mariyaVj** [comment]
`-- bitgo@4.13.0
| +-- argparse@0.1.16
| | +-- underscore@1.7.0
| | `-- underscore.string@2.4.0 deduped
| +-- assert@0.4.9
| | `-- util@0.10.3
| |   `-- inherits@2.0.1
| +-- big.js@3.1.3
| +-- bigi@1.4.0
| +-- bignumber.js@4.0.4
| +-- bitcoinjs-lib@3.3.0 (git+ssh://git@github.com/dabura667/bitcoinjs-lib.git#92c602567bd62dd1b41b717cc7d977c015104f1c)
| | +-- bech32@0.0.3
| | +-- bigi@1.4.0 deduped
| | +-- bip66@1.1.5
| | | `-- safe-buffer@5.1.1 deduped
| | +-- bitcoin-ops@1.3.0
| | +-- bs58check@2.0.2
| | | +-- bs58@4.0.1
| | | | `-- base-x@3.0.2
| | | |   `-- safe-buffer@5.1.1 deduped
| | | `-- create-hash@1.1.3 deduped
| | +-- create-hash@1.1.3 deduped
| | +-- create-hmac@1.1.6 deduped
| | +-- ecurve@1.0.5 deduped
| | +-- merkle-lib@2.0.10
| | +-- pushdata-bitcoin@1.0.1
| | | `-- bitcoin-ops@1.3.0 deduped
| | +-- randombytes@2.0.5
| | | `-- safe-buffer@5.1.1 deduped
| | +-- safe-buffer@5.1.1 deduped
| | +-- typeforce@1.11.7
| | +-- varuint-bitcoin@1.0.4
| | `-- wif@2.0.6
| |   `-- bs58check@1.0.4 deduped
| +-- bitcoinjs-message@2.0.0
| | +-- bs58check@2.0.2
| | | +-- bs58@4.0.1
| | | | `-- base-x@3.0.2 deduped
| | | `-- create-hash@1.1.3 deduped
| | +-- buffer-equals@1.0.4
| | +-- create-hash@1.1.3 deduped
| | +-- secp256k1@3.3.1 deduped
| | `-- varuint-bitcoin@1.0.4 deduped
| +-- bluebird@3.5.1
| +-- body-parser@1.18.2
| | +-- bytes@3.0.0
| | +-- content-type@1.0.4 deduped
| | +-- debug@2.6.9
| | | `-- ms@2.0.0
| | +-- depd@1.1.1 deduped
| | +-- http-errors@1.6.2 deduped
| | +-- iconv-lite@0.4.19
| | +-- on-finished@2.3.0 deduped
| | +-- qs@6.5.1
| | +-- raw-body@2.3.2
| | | +-- bytes@3.0.0 deduped
| | | +-- http-errors@1.6.2 deduped
| | | +-- iconv-lite@0.4.19 deduped
| | | `-- unpipe@1.0.0 deduped
| | `-- type-is@1.6.15 deduped
| +-- bs58@2.0.1
| +-- bs58check@1.0.4
| | `-- bs58@2.0.1 deduped
| +-- create-hmac@1.1.6
| | +-- cipher-base@1.0.4
| | | +-- inherits@2.0.3 deduped
| | | `-- safe-buffer@5.1.1 deduped
| | +-- create-hash@1.1.3 deduped
| | +-- inherits@2.0.3
| | +-- ripemd160@2.0.1
| | | +-- hash-base@2.0.2
| | | | `-- inherits@2.0.3 deduped
| | | `-- inherits@2.0.3 deduped
| | +-- safe-buffer@5.1.1 deduped
| | `-- sha.js@2.4.9
| |   +-- inherits@2.0.3 deduped
| |   `-- safe-buffer@5.1.1 deduped
| +-- ecurve@1.0.5
| | `-- bigi@1.4.0 deduped
| +-- eol@0.5.0
| +-- UNMET OPTIONAL DEPENDENCY ethereumjs-abi@~0.6.2
| +-- ethereumjs-util@4.4.1
| | +-- bn.js@4.11.8 deduped
| | +-- create-hash@1.1.3 deduped
| | +-- UNMET DEPENDENCY keccakjs@^0.2.0
| | +-- rlp@2.0.0 deduped
| | `-- secp256k1@3.2.5 deduped
| +-- express@4.16.2
| | +-- accepts@1.3.4 deduped
| | +-- array-flatten@1.1.1 deduped
| | +-- body-parser@1.18.2 deduped
| | +-- content-disposition@0.5.2 deduped
| | +-- content-type@1.0.4 deduped
| | +-- cookie@0.3.1 deduped
| | +-- cookie-signature@1.0.6 deduped
| | +-- debug@2.6.9 deduped
| | +-- depd@1.1.1 deduped
| | +-- encodeurl@1.0.1 deduped
| | +-- escape-html@1.0.3 deduped
| | +-- etag@1.8.1 deduped
| | +-- finalhandler@1.1.0
| | | +-- debug@2.6.9 deduped
| | | +-- encodeurl@1.0.1 deduped
| | | +-- escape-html@1.0.3 deduped
| | | +-- on-finished@2.3.0 deduped
| | | +-- parseurl@1.3.2 deduped
| | | +-- statuses@1.3.1 deduped
| | | `-- unpipe@1.0.0 deduped
| | +-- fresh@0.5.2
| | +-- merge-descriptors@1.0.1 deduped
| | +-- methods@1.1.2 deduped
| | +-- on-finished@2.3.0 deduped
| | +-- parseurl@1.3.2 deduped
| | +-- path-to-regexp@0.1.7 deduped
| | +-- proxy-addr@2.0.2
| | | +-- forwarded@0.1.2 deduped
| | | `-- ipaddr.js@1.5.2
| | +-- qs@6.5.1 deduped
| | +-- range-parser@1.2.0 deduped
| | +-- safe-buffer@5.1.1 deduped
| | +-- send@0.16.1
| | | +-- debug@2.6.9 deduped
| | | +-- depd@1.1.1 deduped
| | | +-- destroy@1.0.4 deduped
| | | +-- encodeurl@1.0.1 deduped
| | | +-- escape-html@1.0.3 deduped
| | | +-- etag@1.8.1 deduped
| | | +-- fresh@0.5.2 deduped
| | | +-- http-errors@1.6.2 deduped
| | | +-- mime@1.4.1 deduped
| | | +-- ms@2.0.0 deduped
| | | +-- on-finished@2.3.0 deduped
| | | +-- range-parser@1.2.0 deduped
| | | `-- statuses@1.3.1 deduped
| | +-- serve-static@1.13.1
| | | +-- encodeurl@1.0.1 deduped
| | | +-- escape-html@1.0.3 deduped
| | | +-- parseurl@1.3.2 deduped
| | | `-- send@0.16.1 deduped
| | +-- setprototypeof@1.1.0
| | +-- statuses@1.3.1
| | +-- type-is@1.6.15 deduped
| | +-- utils-merge@1.0.1
| | `-- vary@1.1.2 deduped
| +-- http-proxy@1.11.1
| | +-- eventemitter3@1.2.0
| | `-- requires-port@0.0.1
| +-- lodash@4.13.1
| +-- minimist@0.2.0
| +-- moment@2.18.1
| +-- morgan@1.9.0
| | +-- basic-auth@2.0.0
| | | `-- safe-buffer@5.1.1 deduped
| | +-- debug@2.6.9 deduped
| | +-- depd@1.1.1 deduped
| | +-- on-finished@2.3.0 deduped
| | `-- on-headers@1.0.1 deduped
| +-- prova-lib@0.2.9
| | +-- bigi@1.4.2
| | +-- bitcoin-ops@1.3.0 deduped
| | +-- bitcoinjs-lib@3.0.3
| | | +-- bigi@1.4.2 deduped
| | | +-- bip66@1.1.5 deduped
| | | +-- bitcoin-ops@1.3.0 deduped
| | | +-- bs58check@2.0.2 deduped
| | | +-- create-hash@1.1.3 deduped
| | | +-- create-hmac@1.1.6 deduped
| | | +-- ecurve@1.0.5 deduped
| | | +-- merkle-lib@2.0.10 deduped
| | | +-- pushdata-bitcoin@1.0.1 deduped
| | | +-- randombytes@2.0.5 deduped
| | | +-- typeforce@1.10.6 deduped
| | | +-- varuint-bitcoin@1.0.4 deduped
| | | `-- wif@2.0.6 deduped
| | +-- bs58check@2.0.2
| | | +-- bs58@4.0.1
| | | | `-- base-x@3.0.2 deduped
| | | `-- create-hash@1.1.3 deduped
| | +-- ecurve@1.0.5 deduped
| | +-- lodash@4.17.4 deduped
| | +-- secp256k1@3.3.1 deduped
| | +-- typeforce@1.10.6
| | | `-- inherits@2.0.3 deduped
| | `-- varuint-bitcoin@1.0.4 deduped
| +-- ripple-lib@0.17.8
| | +-- babel-polyfill@6.26.0
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- core-js@2.5.1
| | | `-- regenerator-runtime@0.10.5
| | +-- babel-runtime@6.26.0
| | | +-- core-js@2.5.1 deduped
| | | `-- regenerator-runtime@0.11.0
| | +-- bignumber.js@4.1.0
| | +-- https-proxy-agent@1.0.0
| | | +-- agent-base@2.1.1
| | | | +-- extend@3.0.1 deduped
| | | | `-- semver@5.0.3
| | | +-- debug@2.6.3 deduped
| | | `-- extend@3.0.1 deduped
| | +-- jsonschema@1.2.0
| | +-- lodash@4.17.4 deduped
| | +-- ripple-address-codec@2.0.1
| | | +-- hash.js@1.1.3 deduped
| | | `-- x-address-codec@0.7.2
| | |   `-- base-x@1.1.0
| | +-- ripple-binary-codec@0.1.11
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- bn.js@4.11.8 deduped
| | | +-- create-hash@1.1.3 deduped
| | | +-- decimal.js@5.0.8
| | | +-- inherits@2.0.3 deduped
| | | +-- lodash@4.17.4 deduped
| | | `-- ripple-address-codec@2.0.1 deduped
| | +-- ripple-hashes@0.3.1
| | | +-- bignumber.js@4.1.0
| | | +-- create-hash@1.1.3 deduped
| | | +-- ripple-address-codec@2.0.1 deduped
| | | `-- ripple-binary-codec@0.1.11 deduped
| | +-- ripple-keypairs@0.10.0
| | | +-- babel-runtime@5.8.38
| | | | `-- core-js@1.2.7
| | | +-- bn.js@3.3.0
| | | +-- brorand@1.1.0 deduped
| | | +-- elliptic@5.2.1
| | | | +-- bn.js@3.3.0 deduped
| | | | +-- brorand@1.1.0 deduped
| | | | +-- hash.js@1.1.3 deduped
| | | | `-- inherits@2.0.3 deduped
| | | +-- hash.js@1.1.3 deduped
| | | `-- ripple-address-codec@2.0.1 deduped
| | +-- ripple-lib-transactionparser@0.6.2
| | | +-- bignumber.js@4.1.0
| | | `-- lodash@4.17.4 deduped
| | `-- ws@1.1.5
| |   +-- options@0.0.6
| |   `-- ultron@1.0.2
| +-- sanitize-html@1.13.0
| | +-- htmlparser2@3.9.2
| | | +-- domelementtype@1.3.0
| | | +-- domhandler@2.4.1
| | | | `-- domelementtype@1.3.0 deduped
| | | +-- domutils@1.6.2
| | | | +-- dom-serializer@0.1.0
| | | | | +-- domelementtype@1.1.3
| | | | | `-- entities@1.1.1 deduped
| | | | `-- domelementtype@1.3.0 deduped
| | | +-- entities@1.1.1 deduped
| | | +-- inherits@2.0.3 deduped
| | | `-- readable-stream@2.3.3 deduped
| | +-- regexp-quote@0.0.0
| | `-- xtend@4.0.1 deduped
| +-- secp256k1@3.2.5
| | +-- bindings@1.3.0
| | +-- bip66@1.1.5 deduped
| | +-- bn.js@4.11.8 deduped
| | +-- create-hash@1.1.3 deduped
| | +-- drbg.js@1.0.1
| | | +-- browserify-aes@1.1.1
| | | | +-- buffer-xor@1.0.3
| | | | +-- cipher-base@1.0.4 deduped
| | | | +-- create-hash@1.1.3 deduped
| | | | +-- evp_bytestokey@1.0.3
| | | | | +-- md5.js@1.3.4
| | | | | | +-- hash-base@3.0.4
| | | | | | | +-- inherits@2.0.3 deduped
| | | | | | | `-- safe-buffer@5.1.1 deduped
| | | | | | `-- inherits@2.0.3 deduped
| | | | | `-- safe-buffer@5.1.1 deduped
| | | | +-- inherits@2.0.3 deduped
| | | | `-- safe-buffer@5.1.1 deduped
| | | +-- create-hash@1.1.3 deduped
| | | `-- create-hmac@1.1.6 deduped
| | +-- elliptic@6.4.0
| | | +-- bn.js@4.11.8 deduped
| | | +-- brorand@1.1.0
| | | +-- hash.js@1.1.3
| | | | +-- inherits@2.0.3 deduped
| | | | `-- minimalistic-assert@1.0.0 deduped
| | | +-- hmac-drbg@1.0.1
| | | | +-- hash.js@1.1.3 deduped
| | | | +-- minimalistic-assert@1.0.0 deduped
| | | | `-- minimalistic-crypto-utils@1.0.1 deduped
| | | +-- inherits@2.0.3 deduped
| | | +-- minimalistic-assert@1.0.0
| | | `-- minimalistic-crypto-utils@1.0.1
| | +-- nan@2.6.2 deduped
| | `-- prebuild-install@2.3.0
| |   +-- expand-template@1.1.0
| |   +-- github-from-package@0.0.0
| |   +-- minimist@1.2.0
| |   +-- mkdirp@0.5.1 deduped
| |   +-- node-abi@2.1.2
| |   | `-- semver@5.4.1 deduped
| |   +-- noop-logger@0.1.1
| |   +-- npmlog@4.1.2 deduped
| |   +-- os-homedir@1.0.2
| |   +-- pump@1.0.2
| |   | +-- end-of-stream@1.4.0
| |   | | `-- once@1.4.0 deduped
| |   | `-- once@1.4.0 deduped
| |   +-- rc@1.2.2 deduped
| |   +-- simple-get@1.4.3
| |   | +-- once@1.4.0 deduped
| |   | +-- unzip-response@1.0.2
| |   | `-- xtend@4.0.1 deduped
| |   +-- tar-fs@1.16.0
| |   | +-- chownr@1.0.1
| |   | +-- mkdirp@0.5.1 deduped
| |   | +-- pump@1.0.2 deduped
| |   | `-- tar-stream@1.5.4
| |   |   +-- bl@1.2.1
| |   |   | `-- readable-stream@2.3.3 deduped
| |   |   +-- end-of-stream@1.4.0 deduped
| |   |   +-- readable-stream@2.3.3 deduped
| |   |   `-- xtend@4.0.1 deduped
| |   +-- tunnel-agent@0.6.0 deduped
| |   `-- xtend@4.0.1 deduped
| +-- secrets.js-grempe@1.1.0
| +-- superagent@3.5.2
| | +-- component-emitter@1.2.1
| | +-- cookiejar@2.1.1
| | +-- debug@2.6.9 deduped
| | +-- extend@3.0.1 deduped
| | +-- form-data@2.1.4 deduped
| | +-- formidable@1.1.1
| | +-- methods@1.1.2 deduped
| | +-- mime@1.4.1
| | +-- qs@6.5.1 deduped
| | `-- readable-stream@2.3.3
| |   +-- core-util-is@1.0.2 deduped
| |   +-- inherits@2.0.3 deduped
| |   +-- isarray@1.0.0 deduped
| |   +-- process-nextick-args@1.0.7 deduped
| |   +-- safe-buffer@5.1.1 deduped
| |   +-- string_decoder@1.0.3 deduped
| |   `-- util-deprecate@1.0.2 deduped
| +-- superagent-proxy@1.0.2
| | +-- debug@2.6.3 deduped
| | `-- proxy-agent@2.1.0
| |   +-- agent-base@2.1.1 deduped
| |   +-- debug@2.6.3 deduped
| |   +-- extend@3.0.1 deduped
| |   +-- http-proxy-agent@1.0.0
| |   | +-- agent-base@2.1.1 deduped
| |   | +-- debug@2.6.3 deduped
| |   | `-- extend@3.0.1 deduped
| |   +-- https-proxy-agent@1.0.0 deduped
| |   +-- lru-cache@2.6.5
| |   +-- pac-proxy-agent@2.0.0
| |   | +-- agent-base@2.1.1 deduped
| |   | +-- debug@2.6.9
| |   | | `-- ms@2.0.0
| |   | +-- get-uri@2.0.1
| |   | | +-- data-uri-to-buffer@1.2.0
| |   | | +-- debug@2.6.3 deduped
| |   | | +-- extend@3.0.1 deduped
| |   | | +-- file-uri-to-path@1.0.0
| |   | | +-- ftp@0.3.10
| |   | | | +-- readable-stream@1.1.14
| |   | | | | +-- core-util-is@1.0.2 deduped
| |   | | | | +-- inherits@2.0.3 deduped
| |   | | | | +-- isarray@0.0.1
| |   | | | | `-- string_decoder@0.10.31
| |   | | | `-- xregexp@2.0.0
| |   | | `-- readable-stream@2.3.3 deduped
| |   | +-- http-proxy-agent@1.0.0 deduped
| |   | +-- https-proxy-agent@1.0.0 deduped
| |   | +-- pac-resolver@3.0.0
| |   | | +-- co@4.6.0 deduped
| |   | | +-- degenerator@1.0.4
| |   | | | +-- ast-types@0.9.14
| |   | | | +-- escodegen@1.9.0
| |   | | | | +-- esprima@3.1.3
| |   | | | | +-- estraverse@4.2.0 deduped
| |   | | | | +-- esutils@2.0.2 deduped
| |   | | | | +-- optionator@0.8.2 deduped
| |   | | | | `-- source-map@0.5.7
| |   | | | `-- esprima@3.0.0 deduped
| |   | | +-- ip@1.1.5
| |   | | +-- netmask@1.0.6
| |   | | `-- thunkify@2.1.2
| |   | +-- raw-body@2.2.0 deduped
| |   | `-- socks-proxy-agent@3.0.1
| |   |   +-- agent-base@4.1.1
| |   |   | `-- es6-promisify@5.0.0
| |   |   |   `-- es6-promise@4.1.1
| |   |   `-- socks@1.1.10 deduped
| |   `-- socks-proxy-agent@2.1.1
| |     +-- agent-base@2.1.1 deduped
| |     +-- extend@3.0.1 deduped
| |     `-- socks@1.1.10
| |       +-- ip@1.1.5 deduped
| |       `-- smart-buffer@1.1.15
| `-- underscore.string@2.4.0
+-- ethereumjs-util@5.1.2
| +-- babel-preset-es2015@6.24.1
| | +-- babel-plugin-check-es2015-constants@6.22.0
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-arrow-functions@6.22.0
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-block-scoped-functions@6.22.0
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-block-scoping@6.26.0
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-template@6.26.0
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- babel-traverse@6.26.0 deduped
| | | | +-- babel-types@6.26.0 deduped
| | | | +-- babylon@6.18.0 deduped
| | | | `-- lodash@4.17.4 deduped
| | | +-- babel-traverse@6.26.0
| | | | +-- babel-code-frame@6.26.0 deduped
| | | | +-- babel-messages@6.23.0 deduped
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- babel-types@6.26.0 deduped
| | | | +-- babylon@6.18.0 deduped
| | | | +-- debug@2.6.9
| | | | | `-- ms@2.0.0
| | | | +-- globals@9.18.0 deduped
| | | | +-- invariant@2.2.2
| | | | | `-- loose-envify@1.3.1
| | | | |   `-- js-tokens@3.0.2 deduped
| | | | `-- lodash@4.17.4 deduped
| | | +-- babel-types@6.26.0
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- esutils@2.0.2 deduped
| | | | +-- lodash@4.17.4 deduped
| | | | `-- to-fast-properties@1.0.3
| | | `-- lodash@4.17.4 deduped
| | +-- babel-plugin-transform-es2015-classes@6.24.1
| | | +-- babel-helper-define-map@6.26.0
| | | | +-- babel-helper-function-name@6.24.1 deduped
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- babel-types@6.26.0 deduped
| | | | `-- lodash@4.17.4 deduped
| | | +-- babel-helper-function-name@6.24.1
| | | | +-- babel-helper-get-function-arity@6.24.1 deduped
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- babel-template@6.26.0 deduped
| | | | +-- babel-traverse@6.26.0 deduped
| | | | `-- babel-types@6.26.0 deduped
| | | +-- babel-helper-optimise-call-expression@6.24.1
| | | | +-- babel-runtime@6.26.0 deduped
| | | | `-- babel-types@6.26.0 deduped
| | | +-- babel-helper-replace-supers@6.24.1
| | | | +-- babel-helper-optimise-call-expression@6.24.1 deduped
| | | | +-- babel-messages@6.23.0 deduped
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- babel-template@6.26.0 deduped
| | | | +-- babel-traverse@6.26.0 deduped
| | | | `-- babel-types@6.26.0 deduped
| | | +-- babel-messages@6.23.0
| | | | `-- babel-runtime@6.26.0 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-template@6.26.0 deduped
| | | +-- babel-traverse@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-computed-properties@6.24.1
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-template@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-destructuring@6.23.0
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-duplicate-keys@6.24.1
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-for-of@6.23.0
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-function-name@6.24.1
| | | +-- babel-helper-function-name@6.24.1 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-literals@6.22.0
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-modules-amd@6.24.1
| | | +-- babel-plugin-transform-es2015-modules-commonjs@6.26.0 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-template@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-modules-commonjs@6.26.0
| | | +-- babel-plugin-transform-strict-mode@6.24.1
| | | | +-- babel-runtime@6.26.0 deduped
| | | | `-- babel-types@6.26.0 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-template@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-modules-systemjs@6.24.1
| | | +-- babel-helper-hoist-variables@6.24.1
| | | | +-- babel-runtime@6.26.0 deduped
| | | | `-- babel-types@6.26.0 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-template@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-modules-umd@6.24.1
| | | +-- babel-plugin-transform-es2015-modules-amd@6.24.1 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-template@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-object-super@6.24.1
| | | +-- babel-helper-replace-supers@6.24.1 deduped
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-parameters@6.24.1
| | | +-- babel-helper-call-delegate@6.24.1
| | | | +-- babel-helper-hoist-variables@6.24.1 deduped
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- babel-traverse@6.26.0 deduped
| | | | `-- babel-types@6.26.0 deduped
| | | +-- babel-helper-get-function-arity@6.24.1
| | | | +-- babel-runtime@6.26.0 deduped
| | | | `-- babel-types@6.26.0 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-template@6.26.0 deduped
| | | +-- babel-traverse@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-shorthand-properties@6.24.1
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-spread@6.22.0
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-sticky-regex@6.24.1
| | | +-- babel-helper-regex@6.26.0
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- babel-types@6.26.0 deduped
| | | | `-- lodash@4.17.4 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-template-literals@6.22.0
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-typeof-symbol@6.23.0
| | | `-- babel-runtime@6.26.0 deduped
| | +-- babel-plugin-transform-es2015-unicode-regex@6.24.1
| | | +-- babel-helper-regex@6.26.0 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- regexpu-core@2.0.0
| | |   +-- regenerate@1.3.3
| | |   +-- regjsgen@0.2.0
| | |   `-- regjsparser@0.1.5
| | |     `-- jsesc@0.5.0
| | `-- babel-plugin-transform-regenerator@6.26.0
| |   `-- regenerator-transform@0.10.1
| |     +-- babel-runtime@6.26.0 deduped
| |     +-- babel-types@6.26.0 deduped
| |     `-- private@0.1.8 deduped
| +-- babelify@7.3.0
| | +-- babel-core@6.26.0
| | | +-- babel-code-frame@6.26.0 deduped
| | | +-- babel-generator@6.26.0
| | | | +-- babel-messages@6.23.0 deduped
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- babel-types@6.26.0 deduped
| | | | +-- detect-indent@4.0.0
| | | | | `-- repeating@2.0.1
| | | | |   `-- is-finite@1.0.2 deduped
| | | | +-- jsesc@1.3.0
| | | | +-- lodash@4.17.4 deduped
| | | | +-- source-map@0.5.7
| | | | `-- trim-right@1.0.1
| | | +-- babel-helpers@6.24.1
| | | | +-- babel-runtime@6.26.0 deduped
| | | | `-- babel-template@6.26.0 deduped
| | | +-- babel-messages@6.23.0 deduped
| | | +-- babel-register@6.26.0
| | | | +-- babel-core@6.26.0 deduped
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- core-js@2.5.1 deduped
| | | | +-- home-or-tmp@2.0.0
| | | | | +-- os-homedir@1.0.2 deduped
| | | | | `-- os-tmpdir@1.0.2 deduped
| | | | +-- lodash@4.17.4 deduped
| | | | +-- mkdirp@0.5.1 deduped
| | | | `-- source-map-support@0.4.18
| | | |   `-- source-map@0.5.7
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-template@6.26.0 deduped
| | | +-- babel-traverse@6.26.0 deduped
| | | +-- babel-types@6.26.0 deduped
| | | +-- babylon@6.18.0
| | | +-- convert-source-map@1.5.0
| | | +-- debug@2.6.9
| | | | `-- ms@2.0.0
| | | +-- json5@0.5.1
| | | +-- lodash@4.17.4 deduped
| | | +-- minimatch@3.0.4 deduped
| | | +-- path-is-absolute@1.0.1 deduped
| | | +-- private@0.1.8
| | | +-- slash@1.0.0
| | | `-- source-map@0.5.7
| | `-- object-assign@4.1.1 deduped
| +-- bn.js@4.11.8
| +-- create-hash@1.1.3
| | +-- cipher-base@1.0.4 deduped
| | +-- inherits@2.0.3 deduped
| | +-- ripemd160@2.0.1 deduped
| | `-- sha.js@2.4.9 deduped
| +-- ethjs-util@0.1.4
| | +-- is-hex-prefixed@1.0.0
| | `-- strip-hex-prefix@1.0.0
| |   `-- is-hex-prefixed@1.0.0 deduped
| +-- keccak@1.3.0
| | +-- bindings@1.3.0 deduped
| | +-- inherits@2.0.3 deduped
| | +-- nan@2.6.2 deduped
| | +-- prebuild-install@2.3.0 deduped
| | `-- safe-buffer@5.1.1 deduped
| +-- rlp@2.0.0
| `-- secp256k1@3.3.1
|   +-- bindings@1.3.0 deduped
|   +-- bip66@1.1.5 deduped
|   +-- bn.js@4.11.8 deduped
|   +-- create-hash@1.1.3 deduped
|   +-- drbg.js@1.0.1 deduped
|   +-- elliptic@6.4.0 deduped
|   +-- nan@2.6.2 deduped
|   +-- prebuild-install@2.3.0 deduped
|   `-- safe-buffer@5.1.1 deduped
`

**Comment by thomas4019** [comment]
Thanks for including that info. It looks like you're missing one more dependency which is required for ethereum. Can you please run the following?
`npm ethereumjs-abi`

**Comment by mariyaVj** [comment]
Now it is working for me, the issue was when I installed the bitgo package this dependency was not installing properly , because python was not there. when I tried to install the package by npm install ethereumjs-abi, I got the error saying

  `Error: Can't find Python executable "python", you can set the PYTHON env variable.`

Then I solved it by the following solution 
https://stackoverflow.com/questions/23571257/cant-find-python-executable-python

Where I have created the symbolic link by the method  
ln -s /usr/bin/python2.7 /usr/bin/python 

Then the package got installed and now works fine
Appreciate the help of everyone here. Here by closing the issue, Thanks Guys
